server:
  port: 8082

auth:
  jwt:
    secret: "change-me-to-a-long-random-string-at-least-32-chars"

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: order-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        enable.auto.commit: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  r2dbc:
    url: r2dbc:mysql://localhost:3308/order_db?serverZoneId=UTC
    username: root
    password: root

  flyway:
    url: jdbc:mysql://localhost:3308/order_db?serverZoneId=UTC
    user: root
    password: root
    locations: classpath:db/migration

logging:
  level:
    org.springframework.r2dbc.core: INFO
    org.springframework.data.r2dbc: INFO
    io.asyncer.r2dbc.mysql.QUERY: INFO
    io.asyncer.r2dbc.mysql.PARAM: INFO
    org.springframework.security: ${SECURITY_LOG_LEVEL:INFO}
    org.springframework.security.oauth2: ${SECURITY_OAUTH2_LOG_LEVEL:${SECURITY_LOG_LEVEL:INFO}}